name: 'Release'

on:
  push:
    branches:
      - master

jobs:
  github-release:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git-archive-all
    - name: Get version
      id: get_version
      run: |
        output=$(python get_version.py)
        echo "::set-output name=version::$output"
    - name: Create archive
      run: |
        git-archive-all energy-${{ steps.get_version.outputs.version }}.zip
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: energy-${{ steps.get_version.outputs.version }}.zip
        tag_name: ${{ steps.get_version.outputs.version }}
        name: Energy ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
